version: '3.7'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - '3978:3978'
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example_db
    ports:
      - '5433:5432'
    volumes:
      - db_volume:/var/lib/postgresql/data

volumes:
  node_modules:
  db_volume: